### ISSUE TITLE
Credits.txt

### ISSUE THREAD

**Issue by IGNOT** [Oleg720/scpcb-rus#2]
> *Писатели

Может быть, сценаристы?

> Большое спасибо всем, кто поддерживал проект многие годы. - он бы никогда не стал таким, каким является сейчас, без вашей помощи.

В оригинальном тексте первой точки нет. Здесь она, по-моему, тоже не нужна.

> Если Вы внесли свой склад в игру и Вам хотелось бы, чтобы ваше имя было добавлено здесь, Сообщите мне на форуме Undertow Games или contact@undertowgames.com!

Может быть, не «здесь», а «сюда»? «Сообщите» нужно написать с маленькой буквы.

**Comment by Oleg720** [comment]
Спасибо за внимательность. Будет исправлено.
